# Generated by Django 4.2.29 on 2026-03-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GREETING', 'Saudação'), ('PRICING', 'Preço'), ('AVAILABILITY', 'Disponibilidade'), ('SCHEDULING', 'Agendamento'), ('INFO', 'Informações'), ('CLOSING', 'Encerramento')], max_length=50)),
                ('text', models.TextField()),
                ('shortcut', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_replies', to='core.organization')),
            ],
            options={
                'db_table': 'quick_replies',
                'ordering': ['category', 'shortcut'],
                'unique_together': {('organization', 'shortcut')},
            },
        ),
    ]
