# Generated by Django 4.2.29 on 2026-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_replies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickreply',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='quickreply',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='quickreply',
            name='category',
            field=models.CharField(choices=[('GREETING', 'Saudação'), ('PRICING', 'Preço'), ('AVAILABILITY', 'Disponibilidade'), ('SCHEDULING', 'Agendamento'), ('INFO', 'Informações'), ('CLOSING', 'Encerramento')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='quickreply',
            name='shortcut',
            field=models.CharField(max_length=50),
        ),
    ]
