# Generated by Django 4.2.29 on 2026-03-12 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agentconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quick_replies', '0002_alter_quickreply_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickreply',
            options={'ordering': ['sort_order', 'title', 'shortcut']},
        ),
        migrations.AddField(
            model_name='quickreply',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quickreply',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickreply',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quickreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quickreply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_quick_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickreply',
            name='category',
            field=models.CharField(blank=True, choices=[('GREETING', 'Saudação'), ('PRICING', 'Preço'), ('AVAILABILITY', 'Disponibilidade'), ('SCHEDULING', 'Agendamento'), ('INFO', 'Informações'), ('CLOSING', 'Encerramento')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='quickreply',
            name='shortcut',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='quickreply',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='QuickReplyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_reply_categories', to='core.organization')),
            ],
            options={
                'db_table': 'quick_reply_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quickreply',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='quick_replies.quickreplycategory'),
        ),
    ]
