# Generated by Django 4.2.29 on 2026-03-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_is_active_plan_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-4o-mini', max_length=50)),
                ('system_prompt', models.TextField(blank=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('rag_enabled', models.BooleanField(default=False)),
                ('match_threshold', models.FloatField(default=0.75)),
                ('match_count', models.IntegerField(default=5)),
                ('max_history_messages', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='core.organization')),
            ],
            options={
                'db_table': 'agent_configs',
            },
        ),
    ]
