# Generated by Django 4.2.29 on 2026-04-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_agentconfig_off_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymedia',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('DOCUMENT', 'Documento'), ('AUDIO', 'Áudio')], default='IMAGE', max_length=10),
        ),
    ]
