# Generated by Django 4.2.29 on 2026-03-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_gallerymedia_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(default='Border Collie', max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('pedigree_number', models.CharField(blank=True, max_length=100)),
                ('microchip', models.CharField(blank=True, max_length=100)),
                ('tattoo', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('own', 'Plantel próprio'), ('deceased', 'Falecido')], default='available', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_father', to='kennel.dog')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_mother', to='kennel.dog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='core.organization')),
            ],
            options={
                'db_table': 'kennel_dogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mating_date', models.DateField(blank=True, null=True)),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
                ('cbkc_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters_as_father', to='kennel.dog')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters_as_mother', to='kennel.dog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litters', to='core.organization')),
            ],
            options={
                'db_table': 'kennel_litters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LitterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='kennel/litters/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='kennel.litter')),
            ],
            options={
                'db_table': 'kennel_litter_media',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LitterHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccine', 'Vacina'), ('deworming', 'Vermifugação'), ('exam', 'Exame'), ('other', 'Outro')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('next_date', models.DateField(blank=True, null=True)),
                ('vet', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='kennel.litter')),
            ],
            options={
                'db_table': 'kennel_litter_health',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DogMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='kennel/dogs/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='kennel.dog')),
            ],
            options={
                'db_table': 'kennel_dog_media',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DogHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccine', 'Vacina'), ('deworming', 'Vermifugação'), ('exam', 'Exame'), ('other', 'Outro')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('next_date', models.DateField(blank=True, null=True)),
                ('vet', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='kennel.dog')),
            ],
            options={
                'db_table': 'kennel_dog_health',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='origin_litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppies', to='kennel.litter'),
        ),
    ]
