# Generated by Django 4.2.29 on 2026-03-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
