# Generated by Django 4.2.29 on 2026-04-07 20:39

import apps.kennel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0002_add_is_featured_to_litter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogmedia',
            name='file',
            field=models.ImageField(upload_to=apps.kennel.models._dog_media_upload),
        ),
        migrations.AlterField(
            model_name='littermedia',
            name='file',
            field=models.ImageField(upload_to=apps.kennel.models._litter_media_upload),
        ),
    ]
