# Generated by Django 4.2.29 on 2026-05-21 22:40

import apps.kennel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0003_uuid_upload_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='LitterDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_file', models.FileField(upload_to=apps.kennel.models._litter_template_upload)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('field_inventory', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litter_document_templates', to='core.organization')),
            ],
            options={
                'db_table': 'kennel_litter_document_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LitterRegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to=apps.kennel.models._litter_registration_upload)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generated', 'Gerado'), ('failed', 'Falha')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_documents', to='kennel.litter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litter_registration_documents', to='core.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='kennel.litterdocumenttemplate')),
            ],
            options={
                'db_table': 'kennel_litter_registration_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
