# Generated by Django 4.2.29 on 2026-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0004_litter_registration_pdf_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='registration_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
