# Generated by Django 4.2.20 on 2026-09-24 12:10

import apps.kennel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0005_litter_registration_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogmedia',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo')], default='IMAGE', max_length=10),
        ),
        migrations.AlterField(
            model_name='dogmedia',
            name='file',
            field=models.FileField(upload_to=apps.kennel.models._dog_media_upload),
        ),
    ]
