# Generated by Django 4.2.20 on 2026-09-24 19:40

import apps.kennel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0006_dogmedia_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='littermedia',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo')], default='IMAGE', max_length=10),
        ),
        migrations.AlterField(
            model_name='littermedia',
            name='file',
            field=models.FileField(upload_to=apps.kennel.models._litter_media_upload),
        ),
    ]
