# Generated by Django 4.2.29 on 2026-03-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20)),
                ('app_id', models.CharField(default='', max_length=255)),
                ('app_secret', models.CharField(default='', max_length=255)),
                ('access_token', models.TextField(default='')),
                ('phone_number_id', models.CharField(default='', max_length=255)),
                ('business_account_id', models.CharField(default='', max_length=255)),
                ('instagram_account_id', models.CharField(default='', max_length=255)),
                ('page_id', models.CharField(default='', max_length=255)),
                ('webhook_verify_token', models.CharField(default='', max_length=255)),
                ('webhook_url', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_simulated', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('verified', 'Verificado'), ('pending', 'Pendente'), ('failed', 'Falhou')], default='pending', max_length=50)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_providers', to='core.organization')),
            ],
            options={
                'db_table': 'channels_channelprovider',
            },
        ),
    ]
