# Generated by Django 4.2.29 on 2026-03-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_is_active_plan_created_at_and_more'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelprovider',
            name='app_secret',
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='app_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='business_account_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='instagram_account_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_providers', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='page_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='phone_number_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='provider',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], default='whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='webhook_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='webhook_verify_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
