# Generated by Django 4.2.29 on 2026-03-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_remove_channelprovider_app_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelprovider',
            name='app_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='channelprovider',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='channelprovider',
            name='provider',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('messenger', 'Messenger')], default='whatsapp', max_length=20),
        ),
    ]
