# Generated by Django 4.2.29 on 2026-03-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options_and_more'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conversatio_organiz_5d7a7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_convers_3ebb41_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='message',
            name='organization',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=3),
        ),
    ]
