# Generated by Django 4.2.29 on 2026-03-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_channel_conversation_last_message_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=10, null=True),
        ),
    ]
