# Generated by Django 4.2.29 on 2026-03-13 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_conversation_fk_multitenant'),
        ('conversations', '0004_add_msg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='leads.lead'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('lead', 'channel')},
        ),
    ]
