# Generated by Django 4.2.29 on 2026-03-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channelprovider_app_secret_channelprovider_name_and_more'),
        ('core', '0007_initialmessagemedia'),
        ('conversations', '0005_conversation_fk_multitenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Snake_case, apenas letras minúsculas e underscores', max_length=512)),
                ('language', models.CharField(default='pt_BR', max_length=10)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=20)),
                ('header_text', models.TextField(blank=True, help_text='Cabeçalho opcional do template')),
                ('body_text', models.TextField(help_text='Corpo principal. Use {{1}}, {{2}} para variáveis')),
                ('footer_text', models.TextField(blank=True, help_text='Rodapé opcional do template')),
                ('meta_template_id', models.CharField(blank=True, help_text='ID retornado pela Meta após aprovação', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to='channels.channelprovider')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.organization')),
            ],
            options={
                'db_table': 'message_templates',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'name', 'language')},
            },
        ),
    ]
