# Generated by Django 4.2.29 on 2026-03-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_add_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='header_type',
            field=models.CharField(choices=[('NONE', 'Sem cabeçalho'), ('TEXT', 'Texto'), ('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('DOCUMENT', 'Documento')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='header_text',
            field=models.TextField(blank=True, help_text='Cabeçalho de texto (somente quando header_type=TEXT)'),
        ),
    ]
