# Generated by Django 4.2.29 on 2026-03-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_add_header_media_url_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='meta_media_handle',
            field=models.TextField(blank=True, help_text='Handle retornado pela Meta após upload de mídia via Resumable Upload API. Usado na submissão do template.'),
        ),
    ]
