# Generated by Django 4.2.29 on 2026-03-08 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('housing_type', models.CharField(blank=True, choices=[('HOUSE', 'Casa'), ('APT', 'Apartamento'), ('OTHER', 'Outro')], max_length=20, null=True)),
                ('daily_time_minutes', models.IntegerField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('FIRST_DOG', 'Primeiro cachorro'), ('HAD_DOGS', 'Já teve cães'), ('HAD_HIGH_ENERGY', 'Já teve raça de alta energia')], max_length=20, null=True)),
                ('budget_ok', models.CharField(blank=True, choices=[('YES', 'Sim'), ('NO', 'Não'), ('MAYBE', 'Talvez')], max_length=10, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('NOW', 'Agora'), ('THIRTY_DAYS', '30 dias'), ('SIXTY_PLUS', '60+ dias')], max_length=20, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('COMPANION', 'Companhia'), ('SPORT', 'Esporte'), ('WORK', 'Trabalho')], max_length=20, null=True)),
                ('has_kids', models.BooleanField(default=False)),
                ('has_other_pets', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('tier', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('QUALIFYING', 'Qualificando'), ('QUALIFIED', 'Qualificado'), ('HANDOFF', 'Atendimento Humano'), ('CLOSED', 'Fechado')], default='NEW', max_length=20)),
                ('source', models.CharField(choices=[('INSTAGRAM_AD', 'Instagram Ad'), ('ORGANIC', 'Orgânico'), ('OTHER', 'Outro')], default='ORGANIC', max_length=30)),
                ('is_ai_active', models.BooleanField(default=True)),
                ('channels_used', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.organization')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.organization')),
            ],
            options={
                'db_table': 'lead_tags',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='leads.lead')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leadtag')),
            ],
            options={
                'db_table': 'lead_tag_assignments',
                'unique_together': {('lead', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'status'], name='leads_organiz_d92ede_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'tier'], name='leads_organiz_816a73_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'assigned_to'], name='leads_organiz_fcd788_idx'),
        ),
    ]
