# Generated by Django 4.2.29 on 2026-03-09 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_organization_is_active_plan_created_at_and_more'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_organiz_d92ede_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_organiz_816a73_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_organiz_fcd788_idx',
        ),
        migrations.RemoveField(
            model_name='note',
            name='organization',
        ),
        migrations.AddField(
            model_name='lead',
            name='conversation_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, through='leads.LeadTagAssignment', to='leads.leadtag'),
        ),
        migrations.AddField(
            model_name='leadtag',
            name='color',
            field=models.CharField(blank=True, default='#6B7280', max_length=20),
        ),
        migrations.AddField(
            model_name='leadtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='channels_used',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('FIRST_DOG', 'Primeiro cão'), ('HAD_DOGS', 'Já teve cães'), ('HAD_HIGH_ENERGY', 'Já teve raça de alta energia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('HOUSE', 'Casa'), ('APT', 'Apartamento'), ('OTHER', 'Outro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='purpose',
            field=models.CharField(blank=True, choices=[('COMPANION', 'Companheiro'), ('SPORT', 'Esporte'), ('WORK', 'Trabalho')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('INSTAGRAM_AD', 'Anúncio Instagram'), ('ORGANIC', 'Orgânico'), ('OTHER', 'Outro')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'Novo'), ('QUALIFYING', 'Qualificando'), ('QUALIFIED', 'Qualificado'), ('HANDOFF', 'Handoff'), ('CLOSED', 'Fechado')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tier',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='leadtag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leadtag',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_tags', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='leadtagassignment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
