# Generated by Django 4.2.29 on 2026-03-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ab_variant',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
