# Generated by Django 4.2.29 on 2026-03-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_add_ab_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_classification',
            field=models.CharField(blank=True, choices=[('HOT_LEAD', 'Hot Lead'), ('WARM_LEAD', 'Warm Lead'), ('COLD_LEAD', 'Cold Lead')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('HOUSE_Y', 'Casa com pátio'), ('HOUSE_N', 'Casa sem pátio'), ('HOUSE', 'Casa'), ('APT', 'Apartamento'), ('OTHER', 'Outro')], max_length=10, null=True),
        ),
    ]
