# Generated by Django 4.2.29 on 2026-03-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_add_lead_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook_psid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
