# Generated by Django 4.2.29 on 2026-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_add_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
