# Generated by Django 4.2.29 on 2026-03-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_add_ai_profile_to_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_classification',
            field=models.CharField(blank=True, choices=[('HOT_LEAD', 'Hot Lead'), ('WARM_LEAD', 'Warm Lead'), ('COLD_LEAD', 'Cold Lead'), ('DANGER_LEAD', 'Danger Lead')], max_length=15, null=True),
        ),
    ]
