# Generated by Django 4.2.29 on 2026-04-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_add_danger_lead_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('INSTAGRAM_AD', 'Anúncio Instagram'), ('ORGANIC', 'Orgânico'), ('WEBSITE', 'Site'), ('OTHER', 'Outro')], default='OTHER', max_length=20),
        ),
    ]
