# Generated by Django 4.2.29 on 2026-08-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_adfields_leadprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('INSTAGRAM_AD', 'Anúncio Instagram'), ('GOOGLE_AD', 'Anúncio Google'), ('ORGANIC', 'Orgânico'), ('WEBSITE', 'Site'), ('OTHER', 'Outro')], default='OTHER', max_length=20),
        ),
        # NOTA: o `makemigrations` também detectou uma alteração pré-existente e não
        # relacionada (LeadProfile.id: AutoField → BigAutoField, drift antigo do projeto).
        # Removida deliberadamente desta migration para manter esta mudança estritamente
        # aditiva e restrita à feature Omni Ads — deve ser tratada em uma migration própria,
        # separada, se e quando o time decidir fazer essa alteração de schema.
    ]
