# Generated by Django 4.2.29 on 2026-08-31 04:10

import apps.advertising.models
import apps.channels.encrypted_fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kennel', '0005_litter_registration_data'),
        ('leads', '0012_lead_source_google_ad'),
        ('core', '0017_userprofile_kennel_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_ads', 'Google Ads')], default='google_ads', max_length=20)),
                ('external_campaign_id', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('search', 'Pesquisa (Search)')], default='search', max_length=20)),
                ('objective', models.CharField(choices=[('leads', 'Geração de contatos')], default='leads', max_length=20)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Publicando'), ('active', 'Ativa'), ('paused', 'Pausada'), ('error', 'Erro'), ('ended', 'Encerrada')], default='draft', max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('radius_km', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('landing_url', models.URLField(blank=True, default='', max_length=500)),
                ('ad_headlines', models.JSONField(blank=True, default=list)),
                ('ad_descriptions', models.JSONField(blank=True, default=list)),
                ('ad_keywords', models.JSONField(blank=True, default=list)),
                ('client_request_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ad_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('send_qualified_events', models.BooleanField(default=True)),
                ('send_reservation_events', models.BooleanField(default=True)),
                ('send_sale_events', models.BooleanField(default=True)),
                ('default_daily_budget', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_settings', to='core.organization')),
            ],
            options={
                'db_table': 'advertising_settings',
            },
        ),
        migrations.CreateModel(
            name='AdvertisingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_ads', 'Google Ads')], default='google_ads', max_length=20)),
                ('customer_id', models.CharField(help_text='Google Ads customer ID (sem hífens).', max_length=50)),
                ('login_customer_id', models.CharField(blank=True, default='', help_text='Manager Account (MCC) ID, se aplicável.', max_length=50)),
                ('refresh_token', apps.channels.encrypted_fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('error', 'Erro')], default='connected', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_accounts', to='core.organization')),
            ],
            options={
                'db_table': 'advertising_accounts',
                'unique_together': {('organization', 'provider', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='AdLeadAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gclid', models.CharField(blank=True, default='', max_length=200)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=150)),
                ('utm_content', models.CharField(blank=True, default='', max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_attributions', to='advertising.adcampaign')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_attribution', to='leads.lead')),
            ],
            options={
                'db_table': 'ad_lead_attributions',
            },
        ),
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Visita à landing'), ('whatsapp_click', 'Clique no WhatsApp'), ('lead_created', 'Lead criado'), ('qualified_lead', 'Lead qualificado'), ('reservation', 'Reserva'), ('sale', 'Venda')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='advertising.adcampaign')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_events', to='leads.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_events', to='core.organization')),
            ],
            options={
                'db_table': 'ad_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdConversionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gclid', models.CharField(blank=True, default='', max_length=200)),
                ('conversion_action', models.CharField(blank=True, default='', max_length=200)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('event_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('error', 'Erro'), ('skipped', 'Ignorado')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_upload', to='advertising.adevent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_uploads', to='advertising.adcampaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_conversion_uploads', to='core.organization')),
            ],
            options={
                'db_table': 'ad_conversion_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClickToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.advertising.models._generate_click_token, max_length=16, unique=True)),
                ('gclid', models.CharField(blank=True, default='', max_length=200)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=150)),
                ('utm_content', models.CharField(blank=True, default='', max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_tokens', to='advertising.adcampaign')),
                ('litter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_click_tokens', to='kennel.litter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_click_tokens', to='core.organization')),
            ],
            options={
                'db_table': 'ad_click_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='advertising_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertising.advertisingaccount'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='kennel.litter'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='core.organization'),
        ),
        migrations.CreateModel(
            name='AdMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.FloatField(default=0)),
                ('average_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('cost_per_conversion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='advertising.adcampaign')),
            ],
            options={
                'db_table': 'ad_metrics',
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
