# Generated by Django 4.2.29 on 2026-09-15 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_kennel_fields'),
        ('advertising', '0002_register_metrics_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Agente')], max_length=10)),
                ('content', models.TextField()),
                ('actions_taken', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='advertising.adcampaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_chat_messages', to='core.organization')),
            ],
            options={
                'db_table': 'ad_chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
