# Generated by Django 4.2.29 on 2026-09-15 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_kennel_fields'),
        ('advertising', '0003_adchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adleadattribution',
            name='ad_group_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adleadattribution',
            name='ad_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adleadattribution',
            name='gbraid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='adleadattribution',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='adleadattribution',
            name='search_term',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='adleadattribution',
            name='wbraid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='advertisingsettings',
            name='max_auto_budget_change_percent',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='AdCampaignBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField(blank=True, default='')),
                ('objective', models.TextField(blank=True, default='')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('price_info', models.CharField(blank=True, default='', max_length=200)),
                ('primary_conversion', models.CharField(blank=True, default='lead/whatsapp', max_length=100)),
                ('priority_regions', models.JSONField(blank=True, default=dict)),
                ('positive_intent_keywords', models.JSONField(blank=True, default=list)),
                ('negative_keywords', models.JSONField(blank=True, default=list)),
                ('do_not_negate_keywords', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='briefing', to='advertising.adcampaign')),
            ],
            options={
                'db_table': 'ad_campaign_briefings',
            },
        ),
        migrations.CreateModel(
            name='AdAgentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('hypothesis', models.TextField(blank=True, default='')),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.CharField(choices=[('agent', 'Agente'), ('user', 'Usuário (via app)')], default='agent', max_length=10)),
                ('approval_status', models.CharField(choices=[('auto_executed', 'Executado automaticamente'), ('confirmed_by_user', 'Confirmado pelo usuário'), ('rejected', 'Rejeitado')], default='auto_executed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_decisions', to='advertising.adcampaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_agent_decisions', to='core.organization')),
            ],
            options={
                'db_table': 'ad_agent_decisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
