# Generated by Django 4.2.29 on 2026-09-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_adleadattribution_ad_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adclicktoken',
            name='ad_group_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adclicktoken',
            name='ad_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adclicktoken',
            name='gbraid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='adclicktoken',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='adclicktoken',
            name='search_term',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='adclicktoken',
            name='wbraid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
