# Generated by Django 4.2.29 on 2026-09-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0005_litter_registration_data'),
        ('core', '0017_userprofile_kennel_fields'),
        ('advertising', '0005_adclicktoken_ad_group_id_adclicktoken_ad_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaignPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposta'), ('executed', 'Executada'), ('rejected', 'Rejeitada')], default='proposed', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('objective', models.CharField(default='leads', max_length=20)),
                ('campaign_type', models.CharField(default='search', max_length=20)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('radius_km', models.PositiveIntegerField(blank=True, null=True)),
                ('bid_strategy', models.CharField(default='manual_cpc', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('landing_url', models.URLField(blank=True, default='', max_length=500)),
                ('headlines', models.JSONField(blank=True, default=list)),
                ('descriptions', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('negative_keywords', models.JSONField(blank=True, default=list)),
                ('conversions_tracked', models.JSONField(blank=True, default=list)),
                ('tracking_notes', models.TextField(blank=True, default='')),
                ('justification', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('litter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaign_plans', to='kennel.litter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaign_plans', to='core.organization')),
                ('resulting_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_plans', to='advertising.adcampaign')),
            ],
            options={
                'db_table': 'ad_campaign_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
