# Generated by Django 4.2.29 on 2026-09-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0006_adcampaignplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='adchatmessage',
            name='is_proactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisingsettings',
            name='proactive_review_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
