# Generated by Django 4.2.20 on 2026-09-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0009_adcampaignplan_ad_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaign',
            name='region',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='adcampaignplan',
            name='region',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
