# Generated by Django 4.2.29 on 2026-04-07 20:38

import apps.contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_salecontract_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecontract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.contracts.models._contract_pdf_path),
        ),
    ]
